apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akshaylingamaneni/nc-manifests.git'
    targetRevision: main
    path: NC-MANIFESTS/services
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
