apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "uio-bd-ns"
        envSlug: "prod"
        secretsPath: "/grafana"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: grafana-secrets
      secretNamespace: monitoring
      creationPolicy: Owner
      template:
        includeAllSecrets: true
