apiVersion: apps/v1
kind: Deployment
metadata:
  name: convex-backend
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convex-backend
  template:
    metadata:
      labels:
        app: convex-backend
    spec:
      volumes:
        - name: convex-data
          persistentVolumeClaim:
            claimName: convex-pvc
      initContainers:
        - name: create-db
          image: postgres:18
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: convex-secrets
                  key: POSTGRES_URL
            - name: INSTANCE_NAME
              valueFrom:
                secretKeyRef:
                  name: convex-secrets
                  key: INSTANCE_NAME
          command:
            - sh
            - -c
            - |
              psql "$POSTGRES_URL" -tc \
                "SELECT 1 FROM pg_database WHERE datname='$INSTANCE_NAME'" \
              | grep -q 1 \
              || psql "$POSTGRES_URL" -c "CREATE DATABASE \"$INSTANCE_NAME\""
      containers:
        - name: convex-backend
          image: ghcr.io/get-convex/convex-backend:latest
          ports:
            - containerPort: 3210
              name: api
            - containerPort: 3211
              name: site
          envFrom:
            - secretRef:
                name: convex-secrets
          env:
            - name: DO_NOT_REQUIRE_SSL
              value: "1"
            - name: AWS_S3_DISABLE_SSE
              value: "1"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
            - name: CONVEX_CLOUD_ORIGIN
              value: "https://convex-api.neurocollab.in"
            - name: CONVEX_SITE_ORIGIN
              value: "https://convex-site.neurocollab.in"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: convex-data
              mountPath: /convex/data
          readinessProbe:
            httpGet:
              path: /version
              port: 3210
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /version
              port: 3210
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: convex-backend
  namespace: services
spec:
  selector:
    app: convex-backend
  ports:
    - name: api
      port: 3210
      targetPort: 3210
    - name: site
      port: 3211
      targetPort: 3211
