apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ghcr-creds
  namespace: services
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
      secretsScope:
        projectSlug: "uio-bd-ns"
        envSlug: "prod"
        secretsPath: "/services"
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  managedKubeSecretReferences:
    - creationPolicy: Owner
      secretName: ghcr-creds
      secretNamespace: services
      secretType: kubernetes.io/dockerconfigjson
      template:
        includeAllSecrets: false
        data:
          ".dockerconfigjson": >-
            {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
              .DOCKER_SERVER.Value
              .DOCKER_USERNAME.Value
              .DOCKER_PASSWORD.Value
              (printf "%s:%s" .DOCKER_USERNAME.Value .DOCKER_PASSWORD.Value | encodeBase64)
            | encodeBase64 }}
