apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ghcr-creds
  namespace: services
spec:
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "uio-bd-ns"        
        envSlug: "prod"                 
        secretsPath: "/services"        
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: ghcr-creds
      secretNamespace: services
      creationPolicy: Owner
      secretType: kubernetes.io/dockerconfigjson
      template:
        dockerconfigjson:
          server: $DOCKER_SERVER
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          email: $DOCKER_EMAIL
