apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mango-data-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce      
  resources:
    requests:
      storage: 20Gi       
  storageClassName: standard  
