apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      volumes:
        - name: mango-data
          persistentVolumeClaim:
            claimName: mango-data-pvc
      containers:
        - name: mango
          image: ghcr.io/akshaylingamaneni/mango:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mango-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: mango-data
              mountPath: /data
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 45
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 120
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mango
  namespace: services
spec:
  selector:
    app: mango
  ports:
    - port: 8080
      targetPort: 8080
