apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: mango
          image: ghcr.io/akshaylingamaneni/mango:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mango-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mango
  namespace: services
spec:
  selector:
    app: mango
  ports:
    - port: 8080
      targetPort: 8080
