apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: services
data:
  pgbouncer.ini: |
    [databases]
    * = host=postgres.services.svc.cluster.local port=5432

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 25
    min_pool_size = 5
    reserve_pool_size = 5
    reserve_pool_timeout = 3
    max_db_connections = 100
    max_user_connections = 100
    server_round_robin = 0
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    ignore_startup_parameters = extra_float_digits

