apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres.services.svc.cluster.local -p 5432 -U ${POSTGRES_USER}; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
        - name: generate-config
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Escape password for pgbouncer.ini (quote it properly)
              ESCAPED_PASSWORD=$(echo "${DATABASES_PASSWORD}" | sed 's/"/\\"/g')
              cat > /etc/pgbouncer/pgbouncer.ini <<EOF
              [databases]
              * = host=${DATABASES_HOST} port=${DATABASES_PORT} user=${DATABASES_USER} password="${ESCAPED_PASSWORD}" dbname=${DATABASES_DBNAME}
              
              [pgbouncer]
              listen_addr = 0.0.0.0
              listen_port = 6432
              auth_type = any
              pool_mode = ${PGBOUNCER_POOL_MODE}
              ignore_startup_parameters = extra_float_digits
              admin_users = ${DATABASES_USER}
              EOF
              cat /etc/pgbouncer/pgbouncer.ini
          env:
            - name: DATABASES_HOST
              value: postgres.services.svc.cluster.local
            - name: DATABASES_PORT
              value: "5432"
            - name: DATABASES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DATABASES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASES_DBNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: PGBOUNCER_POOL_MODE
              value: "transaction"
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
      containers:
        - name: pgbouncer
          image: pgbouncer/pgbouncer:latest
          command: ["pgbouncer", "-u", "pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
          ports:
            - containerPort: 6432
              name: pgbouncer
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
      volumes:
        - name: pgbouncer-config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: services
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
