apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-secrets
  namespace: services
spec:
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "uio-bd-ns"
        envSlug: "prod"
        secretsPath: "/postgres"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: postgres-secrets
      secretNamespace: services
      creationPolicy: Owner
      template:
        includeAllSecrets: true

