apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweedfs
  namespace: services
spec:
  image: chrislusf/seaweedfs:3.68
  volumeServerDiskCount: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values: [seaweedfs]
  master:
    replicas: 0
    volumePreallocate: true
    volumeSizeLimitMB: 29999
    defaultReplication: "000"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  volume:
    replicas: 0
    storageClassName: microk8s-hostpath
    requests:
      storage: 70Gi
    compactionMBps: 64
    maxVolumeCounts: 2
    rack: "rack1"
    dataCenter: "dc1"
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 4
        memory: 6Gi
  filer:
    replicas: 0
    maxMB: 512
    persistence:
      enabled: true
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 20Gi
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
    s3:
      enabled: true
      # Infisical secret must expose a key named `seaweedfs_s3_config.json`
      # containing the IAM identities JSON payload for the S3 gateway.
      configSecret:
        name: seaweedfs-secrets
        key: seaweedfs_s3_config.json
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2
        memory: 4Gi
    iam: true
  iam:
    replicas: 0
    service:
      type: ClusterIP
    port: 8111
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
