apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocker-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath

