apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: supabase-secrets
  namespace: services
spec:
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "uio-bd-ns"
        envSlug: "prod"
        secretsPath: "/supabase"  # Expected keys documented in services/supabase.yml
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: supabase-secrets
      secretNamespace: services
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        # Expected keys under /supabase:
        # - SUPABASE_DB_PASSWORD, SUPABASE_DB_URL, SUPABASE_JWT_SECRET
        # - SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY, REALTIME_SECRET_KEY_BASE
        # - S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY  (SeaweedFS S3 credentials)
        # - DASHBOARD_USERNAME, DASHBOARD_PASSWORD  (Kong basic auth for Studio)
