apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: argo-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  hostAPI: http://infisical-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "uio-bd-ns"
        envSlug: "prod"          # or "production" if that’s your slug
        secretsPath: "/argo"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: argo-repo-creds
      secretNamespace: argocd
      creationPolicy: Owner
      template:
        includeAllSecrets: true
