apiVersion: secrets.infisical.com/v1alpha1
kind: SecretSync
metadata:
  name: argo-repo-creds
  namespace: argocd
spec:
  managedSecretReference:
    name: argo-repo-creds
    labels:
      argocd.argoproj.io/secret-type: repo-creds
  authTokenSecretReference:
    name: infisical-service-token
    namespace: infisical-operator
  environment: prod
  secretsPath: /argo
