apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: github-secrets
  namespace: app
spec:
  provider:
    github:
      appID: "1872553"
      installationID: "83610140"
      organization: "akshaylingamaneni"
      repository: "mango"
      environment: "prod"
      auth:
        privateKey:
          name: uio-app-private-key
          key: privateKey.pem
